// <auto-generated />
using DestinyMatrix.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DestinyMatrix.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302142316_Update20260302")]
    partial class Update20260302
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("DestinyMatrix.Data.ArcanaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Archetype")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZonesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Arcanas");
                });

            modelBuilder.Entity("DestinyMatrix.Data.ArcanaEntity", b =>
                {
                    b.OwnsOne("DestinyMatrix.Features.DestinyMatrix.EnergyState", "Energy", b1 =>
                        {
                            b1.Property<int>("ArcanaEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Minus")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Plus")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ArcanaEntityId");

                            b1.ToTable("Arcanas");

                            b1.WithOwner()
                                .HasForeignKey("ArcanaEntityId");
                        });

                    b.Navigation("Energy")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
